
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "portfolio"
      POSTGRES_USER: "postgres_user"
      POSTGRES_PASSWORD: "123123"
    ports:
      - "5433:5432"
    volumes:
      - ./pg_portfolio_storage:/var/lib/postgresql/data